import type { Device } from "@/types/device";
import { objects } from "./objects";

export const devices: Device[] = [
  {
    id: "dev1",
    createdAt: new Date(),
    updatedAt: new Date(),
    name: "Принтер HP LaserJet Pro",
    serialNumber: "DSN001",
    status: "ON_OBJECT",
    storage: objects[0],
  },
  {
    id: "dev2",
    createdAt: new Date(),
    updatedAt: new Date(),
    name: "Ноутбук Lenovo ThinkPad X1",
    serialNumber: "DSN002",
    status: "IN_TRANSIT",
    storage: objects[1],
  },
  {
    id: "dev3",
    createdAt: new Date(),
    updatedAt: new Date(),
    name: "Маршрутизатор MikroTik hEX",
    serialNumber: "DSN003",
    status: "IN_REPAIR",
    storage: objects[1],
  },
  {
    id: "dev4",
    createdAt: new Date(),
    updatedAt: new Date(),
    name: "Сканер штрих-кодов Zebra",
    serialNumber: "DSN004",
    status: "ON_OBJECT",
    storage: objects[2],
  },
  {
    id: "dev5",
    createdAt: new Date(),
    updatedAt: new Date(),
    name: 'Монитор LG 27"',
    serialNumber: "DSN005",
    status: "LOST",
    storage: objects[3],
  },
  {
    id: "dev6",
    createdAt: new Date(),
    updatedAt: new Date(),
    name: "Кассовый терминал Evotor",
    serialNumber: "DSN006",
    status: "WRITTEN_OFF",
    storage: objects[2],
  },
  {
    id: "dev7",
    createdAt: new Date(),
    updatedAt: new Date(),
    name: "Сетевой коммутатор D-Link",
    serialNumber: "DSN007",
    status: "ON_OBJECT",
    storage: objects[0],
  },
  {
    id: "dev8",
    createdAt: new Date(),
    updatedAt: new Date(),
    name: "ИБП APC Back-UPS",
    serialNumber: "DSN008",
    status: "IN_TRANSIT",
    storage: objects[1],
  },
  {
    id: "dev9",
    createdAt: new Date(),
    updatedAt: new Date(),
    name: "Ноутбук Apple MacBook Air",
    serialNumber: "DSN009",
    status: "IN_REPAIR",
    storage: objects[0],
  },
  {
    id: "dev10",
    createdAt: new Date(),
    updatedAt: new Date(),
    name: "Планшет POS Samsung",
    serialNumber: "DSN010",
    status: "ON_OBJECT",
    storage: objects[3],
  },
];
